services:
  ksg-next:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        MAIL_HOST: ${MAIL_HOST}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_SCHEME: ${MAIL_SCHEME}
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
        ALERT_TO: ${ALERT_TO}
    container_name: ksg-next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3030
      - HOSTNAME=0.0.0.0
      - DB_FILE=/app/data/app.db
    volumes:
      - ./data:/app/data
    ports:
      - "3030:3030"
    restart: unless-stopped
